stages:
  - version
  - build
  - publish

variables:
      PACKAGE_REGISTRY_PROJECT_ID: 194 # because before_script doesn't have access to CICD custom variables

.only for tagged commit:
  rules:
    - if: "$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED"
      when: on_success
    - when: never

.version package:
  image: node:latest
  stage: version
  before_script:
    - apt-get update -y
    - apt-get install -y gettext jq
  script:
    - jq ".version = \"$CI_COMMIT_TAG\"" package.json > package_tmp.json && mv package_tmp.json package.json
  artifacts:
    paths:
      - package.json
  rules:
    - !reference [.only for tagged commit, rules]

build npm dist:
  image: node:latest  
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 day

publish npm package:
  image: node:latest
  stage: publish
  before_script:
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
    - npm config set "@nf-data-iu3:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
  script:
    - npm publish
  rules:
    - !reference [.only for tagged commit, rules]